### ISSUE TITLE
[BUG] on 1.16.5 or any newer version of the world the cheats piece for the characters don't work and baby and sing traps face don't work ether 

### ISSUE THREAD

**Issue by ckrt12** [Mihro/MNAF-Senary-Saloon#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions:**
 - [x] Minecraft: Java Edition 1.16.5
 - [ ] Optifine 1.16.5 HD_U_G7

**Additional context**

**Comment by Mihro** [comment]
The bug report template needs to be filled in correctly so that the issue can be investigated properly.

But it sounds like you do not have Optifine installed.
Armor pieces and baby/springtrap heads are dependent on Optifine to work. You need the version `Optifine 1.16.5 HD_U_G7`.
The map also can not be played on versions of Minecraft newer than 1.16.5.
